import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ApplicationUrl } from "@/lib/appUrl";
import ReactLenis from "lenis/react";
import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const sans = DM_Sans({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500"]
});

const serif = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["400", "500"]
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App"
  },

  description: "Generated by create next app",

  applicationName: "Create Next App",
  generator: "Next.js",
  keywords: ["Next.js", "React", "Web App", "SaaS", "Frontend", "Full Stack"],
  authors: [{ name: "Your Name", url: ApplicationUrl }],
  creator: "Your Name",
  publisher: "Your Company",

  metadataBase: new URL(ApplicationUrl)

  // alternates: {
  //   canonical: "/"
  // },

  // icons: {
  //   icon: "/favicon.ico",
  //   shortcut: "/favicon-16x16.png",
  //   apple: "/apple-touch-icon.png",
  //   other: [
  //     {
  //       rel: "mask-icon",
  //       url: "/safari-pinned-tab.svg",
  //       color: "#181b1e"
  //     }
  //   ]
  // },

  // manifest: "/site.webmanifest",

  // openGraph: {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  //   url: "https://yourdomain.com",
  //   siteName: "Create Next App",
  //   images: [
  //     {
  //       url: "/og-image.png",
  //       width: 1200,
  //       height: 630,
  //       alt: "Create Next App Preview"
  //     }
  //   ],
  //   locale: "en_US",
  //   type: "website"
  // },

  // twitter: {
  //   card: "summary_large_image",
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  //   creator: "@yourhandle",
  //   images: ["/og-image.png"]
  // },

  // category: "technology",

  // verification: {
  //   google: "GOOGLE_SITE_VERIFICATION_CODE",
  //   yandex: "YANDEX_VERIFICATION_CODE",
  //   yahoo: "YAHOO_VERIFICATION_CODE"
  // },

  // appleWebApp: {
  //   capable: true,
  //   title: "Create Next App",
  //   statusBarStyle: "black-translucent"
  // },

  // formatDetection: {
  //   telephone: false
  // }
};

export const viewport: Viewport = {
  themeColor: "#181b1e"
  // colorScheme: "dark"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={`${sans.variable} ${serif.variable} antialiased`}>
        <ReactLenis root>
          <Navbar />
          {children}
          <Footer />
        </ReactLenis>
        <NextTopLoader
          showSpinner={false}
          color="var(--primary)"
          zIndex={999}
          height={3}
        />
      </body>
    </html>
  );
}
